### ISSUE TITLE
Clean functions file

### ISSUE THREAD

**Issue by sarroutbi** [RedHat-SP-Security/attestation-operator-tests#3]
Function file existing on `TestHelpers/functions.sh` contains dead code. It should be cleaned appropriately

**Comment by sopos** [comment]
Wouldn't it make sense to convert the Test Helpers to a library and share it amog all the operator tests? It will make the maintenance much easier for future. Also some kind of sharing the setup tasks would make sense to me.

**Comment by sarroutbi** [comment]
I understand your point. Right now, it is somehow linked to the operator. For example, regarding installation, the installation of the tang operator is done through operator-sdk, while installation of the attestation operator is done through Helm. I agree some of the functions are repeated in both of them, but I would create a new issue for that
